namespace CodexAccountSwitcher.Core;

public enum AppLanguage
{
    Russian,
    English,
    Chinese,
}

public sealed record LanguageOption(AppLanguage Language, string DisplayName);

public static class Localizer
{
    public static IReadOnlyList<LanguageOption> Options { get; } =
    [
        new(AppLanguage.Russian, "Русский"),
        new(AppLanguage.English, "English"),
        new(AppLanguage.Chinese, "中文"),
    ];

    public static AppLanguage FromStorage(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return AppLanguage.Russian;
        }

        return value.Trim().ToLowerInvariant() switch
        {
            "ru" or "russian" or "русский" => AppLanguage.Russian,
            "en" or "english" => AppLanguage.English,
            "zh" or "chinese" or "中文" => AppLanguage.Chinese,
            _ when Enum.TryParse<AppLanguage>(value, ignoreCase: true, out var parsed) => parsed,
            _ => AppLanguage.Russian,
        };
    }

    public static string ToStorage(AppLanguage language)
    {
        return language switch
        {
            AppLanguage.English => "en",
            AppLanguage.Chinese => "zh",
            _ => "ru",
        };
    }

    public static string Get(AppLanguage language, string key)
    {
        var dictionary = language switch
        {
            AppLanguage.English => English,
            AppLanguage.Chinese => Chinese,
            _ => Russian,
        };

        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        return Russian.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(AppLanguage language, string key, params object?[] args)
    {
        return string.Format(Get(language, key), args);
    }

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>
    {
        ["app.title"] = "Аккаунты Codex",
        ["app.subtitle"] = "переключатель аккаунтов",
        ["menu.main"] = "Меню",
        ["menu.instructions"] = "Инструкция",
        ["menu.limits"] = "Лимиты Codex",
        ["menu.settings"] = "Настройки",
        ["menu.exit"] = "Выход",
        ["menu.service"] = "Сервис",
        ["menu.addAccount"] = "Добавить аккаунт",
        ["menu.cleanLogin"] = "Подготовить чистый вход",
        ["menu.inventory"] = "Инвентаризация файлов",
        ["menu.backup"] = "Создать бэкап входа",
        ["menu.restore"] = "Восстановить последний вход",
        ["menu.fileAuth"] = "Настроить хранение auth.json",
        ["safety.title"] = "Безопасный режим",
        ["safety.text"] = "Меняется только auth.json. Чаты, проекты и MCP остаются общими.",
        ["sidebar.addAccount"] = "Добавить аккаунт",
        ["sidebar.limits"] = "Лимиты Codex",
        ["sidebar.settings"] = "Настройки",
        ["log.title"] = "Последнее событие",
        ["log.createFailed"] = "Не удалось создать журнал приложения.",
        ["log.ready"] = "Готово. Профили, язык и тема управляются из меню «Настройки».",
        ["settings.title"] = "Настройки",
        ["settings.themeTitle"] = "Тема: {0}",
        ["settings.languageTitle"] = "Язык",
        ["settings.profiles"] = "Профили Codex",
        ["settings.profilePlaceholder"] = "Например: рабочий Codex",
        ["settings.add"] = "Добавить",
        ["settings.close"] = "Закрыть",
        ["settings.delete"] = "Удалить",
        ["settings.languageRestart"] = "Язык изменён. Окна, которые уже открыты, обновятся после повторного открытия.",
        ["theme.auto"] = "Автоматически",
        ["theme.dark"] = "Темная тема",
        ["theme.gray"] = "Серая тема",
        ["theme.light"] = "Светлая тема",
        ["theme.auto.short"] = "автоматически",
        ["theme.dark.short"] = "темная",
        ["theme.gray.short"] = "серая",
        ["theme.light.short"] = "светлая",
        ["card.active"] = "активен",
        ["card.ready"] = "готов",
        ["card.empty"] = "пустой",
        ["card.activeText"] = "Сейчас используется в Codex.",
        ["card.readyText"] = "Можно перейти без повторного входа.",
        ["card.emptyText"] = "Профиль создан. Выполните чистый вход и сохраните auth.json.",
        ["card.open"] = "Открыт",
        ["card.switch"] = "Перейти",
        ["card.saveLogin"] = "Сохранить вход",
        ["profile.added"] = "Профиль «{0}» добавлен. Для него можно выполнить чистый вход и сохранить auth.json.",
        ["profile.deleteConfirm"] = "Удалить профиль «{0}» и его сохранённый auth.json, если он есть?",
        ["profile.deleteTitle"] = "Удаление профиля",
        ["backup.created"] = "Резервная копия создана: {0}",
        ["inventory.written"] = "Отчёт инвентаризации записан: {0}",
        ["wizard.title"] = "Добавить аккаунт",
        ["wizard.header"] = "Новый профиль Codex",
        ["wizard.description"] = "Мастер делает всё по шагам. Вы сами входите в аккаунт в Codex, а программа только подготавливает место и сохраняет результат.",
        ["wizard.placeholder"] = "Название профиля, например: личный Codex",
        ["wizard.step1.title"] = "1. Создать профиль",
        ["wizard.step1.text"] = "Программа добавит новый профиль в список, но ещё не будет менять вход Codex.",
        ["wizard.step2.title"] = "2. Открыть Codex для входа",
        ["wizard.step2.text"] = "Программа сделает бэкап, временно уберёт текущий вход и откроет Codex. Войдите там в новый аккаунт вручную.",
        ["wizard.step3.title"] = "3. Сохранить вход",
        ["wizard.step3.text"] = "Когда вход в Codex завершён, вернитесь сюда и сохраните его в созданный профиль.",
        ["wizard.start"] = "Начните с названия профиля.",
        ["wizard.profileCreated"] = "Профиль «{0}» создан. Теперь можно открыть Codex для входа.",
        ["wizard.profileCreatedLog"] = "Профиль «{0}» создан через мастер добавления аккаунта.",
        ["wizard.createFailed"] = "Не удалось создать профиль: {0}",
        ["wizard.createFirst"] = "Сначала создайте профиль.",
        ["wizard.preparing"] = "Готовлю Codex к входу...",
        ["wizard.opened"] = "Codex открыт для входа. Войдите в новый аккаунт в Codex, затем нажмите здесь «Сохранить вход».",
        ["wizard.openFailed"] = "Не удалось открыть Codex для входа: {0}",
        ["wizard.saving"] = "Сохраняю вход в профиль...",
        ["wizard.saved"] = "Готово. Вход сохранён в профиль «{0}».",
        ["wizard.saveFailed"] = "Не удалось сохранить вход: {0}",
        ["wizard.openCodex"] = "Открыть Codex",
        ["wizard.createProfile"] = "Создать профиль",
        ["instructions.title"] = "Инструкция",
        ["instructions.header"] = "Как пользоваться переключателем",
        ["instructions.idea.title"] = "Главная идея",
        ["instructions.idea.text"] = "Программа помогает держать несколько входов Codex рядом. Проекты, чаты, настройки, MCP и инструменты остаются общими. Меняется только вход в аккаунт, который Codex использует сейчас.",
        ["instructions.add.title"] = "Добавить новый аккаунт",
        ["instructions.add.text"] = "Нажмите «Добавить аккаунт». Откроется мастер из трёх шагов.\n1. Введите понятное название, например «рабочий Codex», и нажмите «Создать профиль».\n2. Нажмите «Открыть Codex». Программа сделает бэкап, уберёт текущий вход и откроет Codex на экране входа.\n3. Войдите в нужный аккаунт в Codex, вернитесь в мастер и нажмите «Сохранить вход».",
        ["instructions.master.title"] = "Что важно в мастере",
        ["instructions.master.text"] = "Мастер не входит в аккаунт сам и не нажимает ничего в Codex. Он только готовит безопасное место для входа и сохраняет результат, когда вы подтвердите это кнопкой. Если вход в Codex ещё не завершён, кнопку «Сохранить вход» нажимать рано: программа сообщит, что текущий вход не найден.",
        ["instructions.switch.title"] = "Переключиться между аккаунтами",
        ["instructions.switch.text"] = "На карточке нужного профиля нажмите «Перейти». Программа закроет Codex, аккуратно заменит сохранённый вход и снова откроет Codex уже под выбранным аккаунтом.",
        ["instructions.buttons.title"] = "Что делают основные кнопки",
        ["instructions.buttons.text"] = "«Добавить аккаунт» — открывает мастер добавления нового профиля и входа.\n«Перейти» — включает выбранный сохранённый профиль.\n«Сохранить вход» — запоминает текущий вход Codex в выбранную карточку.\n«Лимиты Codex» — показывает оставшиеся лимиты по всем сохранённым профилям.\n«Настройки» — темы, язык, добавление и удаление профилей.",
        ["instructions.service.title"] = "Меню «Сервис»",
        ["instructions.service.text"] = "«Инвентаризация файлов» — делает безопасный список файлов Codex Home без содержимого токенов.\n«Создать бэкап входа» — сохраняет текущий вход перед ручными действиями.\n«Восстановить последний вход» — возвращает самый свежий сохранённый вход.\n«Настроить хранение auth.json» — включает файловое хранение входа, чтобы переключатель мог работать.",
        ["instructions.rule.title"] = "Важное правило",
        ["instructions.rule.text"] = "Когда записываете несколько аккаунтов, не выходите из Codex обычной кнопкой logout. Такой выход может отозвать сохранённый refresh token, и профиль перестанет открываться без повторного входа.",
        ["limits.title"] = "Лимиты Codex",
        ["limits.header"] = "Лимиты всех профилей",
        ["limits.description"] = "Программа проверяет каждый сохранённый вход отдельно. Токены не выводятся, не пишутся в журнал и не сохраняются в базу.",
        ["limits.refreshHint"] = "Нажмите «Обновить», чтобы проверить все сохранённые входы.",
        ["limits.refresh"] = "Обновить",
        ["limits.refreshing"] = "Обновляю лимиты всех профилей...",
        ["limits.updating"] = "обновляю...",
        ["limits.notSaved"] = "вход не сохранён",
        ["limits.updated"] = "обновлено",
        ["limits.checked"] = "Проверено профилей: {0}. Успешно обновлено: {1}.",
        ["limits.failed"] = "Не удалось обновить лимиты: {0}",
        ["limits.profile"] = "Профиль",
        ["limits.fiveHour"] = "5 часов",
        ["limits.week"] = "Неделя",
        ["limits.state"] = "Состояние",
        ["limits.ready"] = "готов к проверке",
        ["limits.unknownReset"] = "сброс: неизвестно",
        ["limits.reset"] = "сброс: {0}",
        ["status.unknown"] = "Активный профиль неизвестен",
        ["status.active"] = "Сейчас активен {0}",
        ["status.activeSuffix"] = "активен",
        ["error.prefix"] = "ОШИБКА: {0}",
        ["firstRun.title"] = "Первый запуск",
        ["firstRun.notFound"] = "Папка Codex не найдена автоматически. Укажите папку .codex вручную или выберите папку пользователя, внутри которой есть .codex.",
        ["firstRun.folderDescription"] = "Выберите папку .codex или папку, внутри которой находится .codex",
        ["firstRun.invalidTitle"] = "Папка Codex",
        ["firstRun.invalidFolder"] = "Выбранная папка не похожа на Codex Home. Нужна папка .codex или папка с auth.json, config.toml, sessions либо _account_profiles.",
        ["common.close"] = "Закрыть",
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["app.title"] = "Codex Accounts",
        ["app.subtitle"] = "account switcher",
        ["menu.main"] = "Menu",
        ["menu.instructions"] = "Guide",
        ["menu.limits"] = "Codex Limits",
        ["menu.settings"] = "Settings",
        ["menu.exit"] = "Exit",
        ["menu.service"] = "Service",
        ["menu.addAccount"] = "Add account",
        ["menu.cleanLogin"] = "Prepare clean sign-in",
        ["menu.inventory"] = "File inventory",
        ["menu.backup"] = "Back up sign-in",
        ["menu.restore"] = "Restore latest sign-in",
        ["menu.fileAuth"] = "Configure auth.json storage",
        ["safety.title"] = "Safe mode",
        ["safety.text"] = "Only auth.json changes. Chats, projects, and MCP stay shared.",
        ["sidebar.addAccount"] = "Add account",
        ["sidebar.limits"] = "Codex Limits",
        ["sidebar.settings"] = "Settings",
        ["log.title"] = "Latest event",
        ["log.createFailed"] = "Could not create the application event log.",
        ["log.ready"] = "Ready. Profiles, language, and theme are managed from Settings.",
        ["settings.title"] = "Settings",
        ["settings.themeTitle"] = "Theme: {0}",
        ["settings.languageTitle"] = "Language",
        ["settings.profiles"] = "Codex profiles",
        ["settings.profilePlaceholder"] = "Example: work Codex",
        ["settings.add"] = "Add",
        ["settings.close"] = "Close",
        ["settings.delete"] = "Delete",
        ["settings.languageRestart"] = "Language changed. Already open windows update when reopened.",
        ["theme.auto"] = "Automatic",
        ["theme.dark"] = "Dark theme",
        ["theme.gray"] = "Gray theme",
        ["theme.light"] = "Light theme",
        ["theme.auto.short"] = "automatic",
        ["theme.dark.short"] = "dark",
        ["theme.gray.short"] = "gray",
        ["theme.light.short"] = "light",
        ["card.active"] = "active",
        ["card.ready"] = "ready",
        ["card.empty"] = "empty",
        ["card.activeText"] = "Currently used by Codex.",
        ["card.readyText"] = "Can switch without signing in again.",
        ["card.emptyText"] = "Profile created. Complete a clean sign-in and save auth.json.",
        ["card.open"] = "Open",
        ["card.switch"] = "Switch",
        ["card.saveLogin"] = "Save sign-in",
        ["profile.added"] = "Profile \"{0}\" was added. You can complete a clean sign-in and save auth.json for it.",
        ["profile.deleteConfirm"] = "Delete profile \"{0}\" and its saved auth.json, if it exists?",
        ["profile.deleteTitle"] = "Delete profile",
        ["backup.created"] = "Backup created: {0}",
        ["inventory.written"] = "Inventory report written: {0}",
        ["wizard.title"] = "Add account",
        ["wizard.header"] = "New Codex profile",
        ["wizard.description"] = "The wizard works step by step. You sign in to Codex yourself; the app only prepares the profile and saves the result.",
        ["wizard.placeholder"] = "Profile name, for example: personal Codex",
        ["wizard.step1.title"] = "1. Create profile",
        ["wizard.step1.text"] = "The app adds a new profile to the list, but does not change the current Codex sign-in yet.",
        ["wizard.step2.title"] = "2. Open Codex for sign-in",
        ["wizard.step2.text"] = "The app creates a backup, temporarily removes the current sign-in, and opens Codex. Sign in to the new account there.",
        ["wizard.step3.title"] = "3. Save sign-in",
        ["wizard.step3.text"] = "After sign-in is complete in Codex, return here and save it into the created profile.",
        ["wizard.start"] = "Start with a profile name.",
        ["wizard.profileCreated"] = "Profile \"{0}\" was created. You can now open Codex for sign-in.",
        ["wizard.profileCreatedLog"] = "Profile \"{0}\" was created with the add-account wizard.",
        ["wizard.createFailed"] = "Could not create profile: {0}",
        ["wizard.createFirst"] = "Create the profile first.",
        ["wizard.preparing"] = "Preparing Codex for sign-in...",
        ["wizard.opened"] = "Codex is open for sign-in. Sign in to the new account in Codex, then click \"Save sign-in\" here.",
        ["wizard.openFailed"] = "Could not open Codex for sign-in: {0}",
        ["wizard.saving"] = "Saving sign-in to the profile...",
        ["wizard.saved"] = "Done. Sign-in saved to profile \"{0}\".",
        ["wizard.saveFailed"] = "Could not save sign-in: {0}",
        ["wizard.openCodex"] = "Open Codex",
        ["wizard.createProfile"] = "Create profile",
        ["instructions.title"] = "Guide",
        ["instructions.header"] = "How to use the switcher",
        ["instructions.idea.title"] = "Main idea",
        ["instructions.idea.text"] = "The app keeps several Codex sign-ins side by side. Projects, chats, settings, MCP, and tools stay shared. Only the account sign-in currently used by Codex changes.",
        ["instructions.add.title"] = "Add a new account",
        ["instructions.add.text"] = "Click \"Add account\". A three-step wizard opens.\n1. Enter a clear name, for example \"work Codex\", and click \"Create profile\".\n2. Click \"Open Codex\". The app creates a backup, removes the current sign-in, and opens Codex on the sign-in screen.\n3. Sign in to the needed account in Codex, return to the wizard, and click \"Save sign-in\".",
        ["instructions.master.title"] = "Important wizard behavior",
        ["instructions.master.text"] = "The wizard does not sign in automatically and does not click anything inside Codex. It only prepares a safe place for the sign-in and saves the result after you confirm it. If Codex sign-in is not complete yet, do not click \"Save sign-in\": the app will say that the current sign-in was not found.",
        ["instructions.switch.title"] = "Switch between accounts",
        ["instructions.switch.text"] = "Click \"Switch\" on the needed profile card. The app closes Codex, replaces the saved sign-in carefully, and opens Codex under the selected account.",
        ["instructions.buttons.title"] = "Main buttons",
        ["instructions.buttons.text"] = "\"Add account\" opens the wizard for a new profile and sign-in.\n\"Switch\" enables the selected saved profile.\n\"Save sign-in\" stores the current Codex sign-in in the selected card.\n\"Codex Limits\" shows remaining limits for all saved profiles.\n\"Settings\" controls themes, language, and profile management.",
        ["instructions.service.title"] = "Service menu",
        ["instructions.service.text"] = "\"File inventory\" writes a safe list of Codex Home files without token contents.\n\"Back up sign-in\" saves the current sign-in before manual actions.\n\"Restore latest sign-in\" restores the most recent saved sign-in.\n\"Configure auth.json storage\" enables file-backed sign-in storage so the switcher can work.",
        ["instructions.rule.title"] = "Important rule",
        ["instructions.rule.text"] = "When recording several accounts, do not use the normal logout button in Codex. Logout can revoke the saved refresh token, and the profile may stop opening without signing in again.",
        ["limits.title"] = "Codex Limits",
        ["limits.header"] = "Limits for all profiles",
        ["limits.description"] = "The app checks every saved sign-in separately. Tokens are not displayed, written to the log, or stored in the database.",
        ["limits.refreshHint"] = "Click \"Refresh\" to check all saved sign-ins.",
        ["limits.refresh"] = "Refresh",
        ["limits.refreshing"] = "Refreshing limits for all profiles...",
        ["limits.updating"] = "updating...",
        ["limits.notSaved"] = "sign-in not saved",
        ["limits.updated"] = "updated",
        ["limits.checked"] = "Profiles checked: {0}. Successfully updated: {1}.",
        ["limits.failed"] = "Could not refresh limits: {0}",
        ["limits.profile"] = "Profile",
        ["limits.fiveHour"] = "5 hours",
        ["limits.week"] = "Week",
        ["limits.state"] = "State",
        ["limits.ready"] = "ready to check",
        ["limits.unknownReset"] = "reset: unknown",
        ["limits.reset"] = "reset: {0}",
        ["status.unknown"] = "Active profile is unknown",
        ["status.active"] = "Currently active: {0}",
        ["status.activeSuffix"] = "active",
        ["error.prefix"] = "ERROR: {0}",
        ["firstRun.title"] = "First launch",
        ["firstRun.notFound"] = "Codex folder was not found automatically. Select the .codex folder manually, or select the user folder that contains .codex.",
        ["firstRun.folderDescription"] = "Select the .codex folder or a folder that contains .codex",
        ["firstRun.invalidTitle"] = "Codex folder",
        ["firstRun.invalidFolder"] = "The selected folder does not look like Codex Home. Select .codex or a folder with auth.json, config.toml, sessions, or _account_profiles.",
        ["common.close"] = "Close",
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["app.title"] = "Codex 账号",
        ["app.subtitle"] = "账号切换器",
        ["menu.main"] = "菜单",
        ["menu.instructions"] = "说明",
        ["menu.limits"] = "Codex 限额",
        ["menu.settings"] = "设置",
        ["menu.exit"] = "退出",
        ["menu.service"] = "服务",
        ["menu.addAccount"] = "添加账号",
        ["menu.cleanLogin"] = "准备全新登录",
        ["menu.inventory"] = "文件清单",
        ["menu.backup"] = "备份登录",
        ["menu.restore"] = "恢复最近登录",
        ["menu.fileAuth"] = "配置 auth.json 存储",
        ["safety.title"] = "安全模式",
        ["safety.text"] = "只更改 auth.json。聊天、项目和 MCP 保持共享。",
        ["sidebar.addAccount"] = "添加账号",
        ["sidebar.limits"] = "Codex 限额",
        ["sidebar.settings"] = "设置",
        ["log.title"] = "最新事件",
        ["log.createFailed"] = "无法创建应用事件日志。",
        ["log.ready"] = "就绪。配置文件、语言和主题可在设置中管理。",
        ["settings.title"] = "设置",
        ["settings.themeTitle"] = "主题：{0}",
        ["settings.languageTitle"] = "语言",
        ["settings.profiles"] = "Codex 配置文件",
        ["settings.profilePlaceholder"] = "例如：工作 Codex",
        ["settings.add"] = "添加",
        ["settings.close"] = "关闭",
        ["settings.delete"] = "删除",
        ["settings.languageRestart"] = "语言已更改。已打开的窗口重新打开后会更新。",
        ["theme.auto"] = "自动",
        ["theme.dark"] = "深色主题",
        ["theme.gray"] = "灰色主题",
        ["theme.light"] = "浅色主题",
        ["theme.auto.short"] = "自动",
        ["theme.dark.short"] = "深色",
        ["theme.gray.short"] = "灰色",
        ["theme.light.short"] = "浅色",
        ["card.active"] = "活动",
        ["card.ready"] = "就绪",
        ["card.empty"] = "空",
        ["card.activeText"] = "Codex 当前正在使用。",
        ["card.readyText"] = "可以无需重新登录切换。",
        ["card.emptyText"] = "配置文件已创建。完成全新登录并保存 auth.json。",
        ["card.open"] = "已打开",
        ["card.switch"] = "切换",
        ["card.saveLogin"] = "保存登录",
        ["profile.added"] = "配置文件“{0}”已添加。你可以为它执行全新登录并保存 auth.json。",
        ["profile.deleteConfirm"] = "删除配置文件“{0}”以及它保存的 auth.json（如果存在）？",
        ["profile.deleteTitle"] = "删除配置文件",
        ["backup.created"] = "备份已创建：{0}",
        ["inventory.written"] = "文件清单报告已写入：{0}",
        ["wizard.title"] = "添加账号",
        ["wizard.header"] = "新的 Codex 配置文件",
        ["wizard.description"] = "向导会按步骤进行。你自己在 Codex 中登录；程序只准备位置并保存结果。",
        ["wizard.placeholder"] = "配置文件名称，例如：个人 Codex",
        ["wizard.step1.title"] = "1. 创建配置文件",
        ["wizard.step1.text"] = "程序会把新配置文件加入列表，但暂时不会改变 Codex 当前登录。",
        ["wizard.step2.title"] = "2. 打开 Codex 登录",
        ["wizard.step2.text"] = "程序会创建备份，临时移除当前登录并打开 Codex。请在那里手动登录新账号。",
        ["wizard.step3.title"] = "3. 保存登录",
        ["wizard.step3.text"] = "Codex 登录完成后，回到这里并把登录保存到创建的配置文件中。",
        ["wizard.start"] = "请先填写配置文件名称。",
        ["wizard.profileCreated"] = "配置文件“{0}”已创建。现在可以打开 Codex 登录。",
        ["wizard.profileCreatedLog"] = "已通过添加账号向导创建配置文件“{0}”。",
        ["wizard.createFailed"] = "无法创建配置文件：{0}",
        ["wizard.createFirst"] = "请先创建配置文件。",
        ["wizard.preparing"] = "正在准备 Codex 登录...",
        ["wizard.opened"] = "Codex 已打开用于登录。请在 Codex 中登录新账号，然后回到这里点击“保存登录”。",
        ["wizard.openFailed"] = "无法打开 Codex 登录：{0}",
        ["wizard.saving"] = "正在把登录保存到配置文件...",
        ["wizard.saved"] = "完成。登录已保存到配置文件“{0}”。",
        ["wizard.saveFailed"] = "无法保存登录：{0}",
        ["wizard.openCodex"] = "打开 Codex",
        ["wizard.createProfile"] = "创建配置文件",
        ["instructions.title"] = "说明",
        ["instructions.header"] = "如何使用切换器",
        ["instructions.idea.title"] = "基本思路",
        ["instructions.idea.text"] = "程序帮助你并排保存多个 Codex 登录。项目、聊天、设置、MCP 和工具保持共享。改变的只有 Codex 当前使用的账号登录。",
        ["instructions.add.title"] = "添加新账号",
        ["instructions.add.text"] = "点击“添加账号”。会打开三步向导。\n1. 输入清晰名称，例如“工作 Codex”，然后点击“创建配置文件”。\n2. 点击“打开 Codex”。程序会创建备份，移除当前登录，并打开 Codex 登录界面。\n3. 在 Codex 中登录需要的账号，回到向导并点击“保存登录”。",
        ["instructions.master.title"] = "向导注意事项",
        ["instructions.master.text"] = "向导不会自动登录账号，也不会在 Codex 中点击任何内容。它只准备安全的登录位置，并在你确认后保存结果。如果 Codex 登录尚未完成，不要过早点击“保存登录”：程序会提示找不到当前登录。",
        ["instructions.switch.title"] = "在账号之间切换",
        ["instructions.switch.text"] = "在需要的配置文件卡片上点击“切换”。程序会关闭 Codex，安全替换保存的登录，然后用选中的账号重新打开 Codex。",
        ["instructions.buttons.title"] = "主要按钮",
        ["instructions.buttons.text"] = "“添加账号”打开新配置文件和登录向导。\n“切换”启用选中的已保存配置文件。\n“保存登录”把当前 Codex 登录保存到选中的卡片。\n“Codex 限额”显示所有已保存配置文件的剩余额度。\n“设置”管理主题、语言、添加和删除配置文件。",
        ["instructions.service.title"] = "服务菜单",
        ["instructions.service.text"] = "“文件清单”创建安全的 Codex Home 文件列表，不包含令牌内容。\n“备份登录”在手动操作前保存当前登录。\n“恢复最近登录”恢复最近保存的登录。\n“配置 auth.json 存储”启用文件登录存储，让切换器可以工作。",
        ["instructions.rule.title"] = "重要规则",
        ["instructions.rule.text"] = "保存多个账号时，不要使用 Codex 的普通 logout 按钮。普通退出可能撤销保存的 refresh token，导致配置文件无法免登录打开。",
        ["limits.title"] = "Codex 限额",
        ["limits.header"] = "所有配置文件的限额",
        ["limits.description"] = "程序会分别检查每个已保存登录。令牌不会显示、不会写入日志，也不会保存到数据库。",
        ["limits.refreshHint"] = "点击“刷新”检查所有已保存登录。",
        ["limits.refresh"] = "刷新",
        ["limits.refreshing"] = "正在刷新所有配置文件的限额...",
        ["limits.updating"] = "正在更新...",
        ["limits.notSaved"] = "登录未保存",
        ["limits.updated"] = "已更新",
        ["limits.checked"] = "已检查配置文件：{0}。成功更新：{1}。",
        ["limits.failed"] = "无法刷新限额：{0}",
        ["limits.profile"] = "配置文件",
        ["limits.fiveHour"] = "5 小时",
        ["limits.week"] = "每周",
        ["limits.state"] = "状态",
        ["limits.ready"] = "可检查",
        ["limits.unknownReset"] = "重置：未知",
        ["limits.reset"] = "重置：{0}",
        ["status.unknown"] = "活动配置文件未知",
        ["status.active"] = "当前活动：{0}",
        ["status.activeSuffix"] = "活动",
        ["error.prefix"] = "错误：{0}",
        ["firstRun.title"] = "首次启动",
        ["firstRun.notFound"] = "未能自动找到 Codex 文件夹。请手动选择 .codex 文件夹，或选择包含 .codex 的用户文件夹。",
        ["firstRun.folderDescription"] = "选择 .codex 文件夹，或选择包含 .codex 的文件夹",
        ["firstRun.invalidTitle"] = "Codex 文件夹",
        ["firstRun.invalidFolder"] = "所选文件夹看起来不是 Codex Home。请选择 .codex，或包含 auth.json、config.toml、sessions 或 _account_profiles 的文件夹。",
        ["common.close"] = "关闭",
    };
}
